### PR TITLE
When using (*JsonParseNode).GetXValue methods it panics fix

### LINKED ISSUE #142: [BUG] When using (*JsonParseNode).GetXValue methods it panics
When using (*JsonParseNode).GetXValue methods it panics due to the value being assert as specific type when it's not.

module version: 1.0.7
golang version: 1.22.5
OS: Window 11

minimum reproducible code:
```golang
package main

import (
	"log"

	jsonserialization "github.com/microsoft/kiota-serialization-json-go"
)

func main() {
	data := []byte(`"I am not a float"`)
	node, _ := jsonserialization.NewJsonParseNode(data)
	float, err := node.GetFloat64Value()
	if err != nil {
		log.Print(err)
		return
	}
	log.Print(float)
	return
}
```

console output:
```bash
panic: interface conversion: interface {} is *string, not *float64

goroutine 1 [running]:
github.com/microsoft/kiota-serialization-json-go.(*JsonParseNode).GetFloat64Value(0xc000068620)
	.../go/pkg/mod/github.com/microsoft/kiota-serialization-json-go@v1.0.7/json_parse_node.go:463 +0xb2
main.main()
	.../min.go:12 +0x105
```

### PR DESCRIPTION
**Pull request by michaeldcanady**
Added utils for converting from like types to others:
ex:
- int8 -> float64
- float32 -> float64
- float64 -> int8 (as long as it doesn't exceed int8 max and/or have a decimal place)
doesn't convert between non-like types:
bool(true) -/-> "true"
int8(1) -/-> bool(true)

Fixes #142

### CODE REVIEW

File: util.go [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+
+// as converts the value to the type T.
+func as[T any](in interface{}, out T) error {
+	// No point in trying anything if already nil
+	if in == nil {
+		return nil
+	}
+
+	// Make sure nothing is a pointer
+	valValue := reflect.ValueOf(in)
```
Comment (baywet) [inline util.go:55]: while I understand the benefits of the approach for numeric types and make sure a conversion is possible/desirable, I'm a bit worried about the potential performance impact of using reflection for the other types.
Have we considered a hybrid approach here? where string/bool/etc... would rely on type assertions and numeric types would rely on this util method?

**Review by baywet — COMMENTED** [review]
Thanks for the contribution! I did leave one question about the impact here.

File: util.go (hunk 1 above)
Comment (michaeldcanady) [reply util.go:74]: just to make sure I am understanding, your recommendation would be to have only numeric types implement the as function and the "other" types only use type assertions?
ex:
numeric
```golang
func (n *JsonParseNode) GetInt8Value() (*int8, error) {
	if isNil(n) || isNil(n.value) {
		return nil, nil
	}
	var val int8

	if err := as(n.value, &val); err != nil {
		return nil, err
	}

	return &val, nil
}
```
string
```golang
func (n *JsonParseNode) GetStringValue() (*string, error) {
	if isNil(n) || isNil(n.value) {
		return nil, nil
	}
	
       val, ok := n.value.(string)
       if !ok {
          return nil, fmt.Errorf("value '%v' is not compatible with type string", n.value)
       }

	return &val, nil
}
```

Comment (michaeldcanady) [reply util.go:74]: The error would need to be tweaked since it's a memory address but not really relevant.

Comment (baywet) [reply util.go:74]: correct, that's the question I was asking.

Comment (michaeldcanady) [reply util.go:74]: I don't see any reason not to except for a weird edge case, which shouldn't happen without user error, where the value is set to a double pointer or a string nested in an interface...?

Comment (michaeldcanady) [reply util.go:74]: for example this would error:
```golang
func main() {

	str := "str"
	strPtr := &str

	node, _ := jsonserialization.NewJsonParseNode([]byte(`"dfsdfds"`))
	node.SetValue(&strPtr)

	val, err := node.GetStringValue()
	if err != nil {
		log.Fatal(err)
	}
	log.Println(val)
}
```
It's just a matter of how much you want to "protect the user" vs what is the performance impact. It might be worth testing it in a dev build, have an intensive object, and compare the two.

Comment (baywet) [reply util.go:74]: Thanks for calling this out, this was an oversight on our end, SetValue should never have been public to begin with. I put together a PR to address this. https://github.com/microsoft/kiota-serialization-json-go/pull/145
Do you have other scenarios where you think the change I'm recommending could be problematic?

Comment (michaeldcanady) [reply util.go:74]: Since `SetValue` will be effectively removed. I can't see any other concerns since only valid JSON will be imported. I can make the change for non-number types.

**Comment by michaeldcanady** [comment]
reopening, it closed, by mistake, when I went to resolve the conflicts

**Review by baywet — DISMISSED** [review]
Thank you for making the changes!
Can you also add an entry to the changelog please? (patch bump, changed, today's date)
@andrueastman for final review and merge/publish

**Comment by michaeldcanady** [comment]
> Thank you for making the changes! Can you also add an entry to the changelog please? (patch bump, changed, today's date) @andrueastman for final review and merge/publish

Just added, let me know if any adjustments should be made to the verbiage!

**Review by baywet — APPROVED** [review]

**Review by andrueastman — APPROVED** [review]
Thanks for the contribution here @michaeldcanady
